var warrior = {
  "arms": {
        "image": "background-warrior-arms.png",
    "total": 0,
    "max": 60,
    "talents": [
      {
            "name": "Improved Heroic Strike",
            "description": "Reduces the cost of your Heroic Strike ability by %p rage point(s).",
            "values": {
                "%p": 1
            },
            "id": 0,
            "row": 0,
            "col": 0,
            "max": 3,
            "current": 0,
            "image": "ability_rogue_ambush.png"
        },
      {
            "name": "Deflection",
            "description": "Increases your Parry chance by %p%.",
            "values": {
                "%p": 1
            },
            "id": 1,
            "row": 0,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "ability_parry.png"
        },
      {
            "name": "Improved Rend",
            "description": "Increases the bleed damage done by your Rend ability by %p%.",
            "values": {
                "%p": 25
            },
            "id": 2,
            "row": 0,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "ability_gouge.png"
        },


      {
            "name": "Improved Charge",
            "description": "Increases the amount of rage generated by your Charge ability by %p.",
            "values": {
                "%p": 3
            },
            "id": 3,
            "row": 1,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "ability_warrior_charge.png"
        },
      {
            "name": "Iron Will",
            "description": "Increases your chance to resist Stun and Charm effects by an additional %p%.",
            "values": {
                "%p": 3
            },
            "id": 4,
            "row": 1,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "spell_magic_magearmor.png"
        },
      {
            "name": "Improved Thunder Clap",
            "description": "Reduces the cost of your Thunder Clap by %p rage point and increases the damage by %d% and the slowing effect by an additional %s%.",
            "values": {
                "%p": 1,
                "%d": 40,
                "%s": 4
            },
            "id": 5,
            "row": 1,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "ability_thunderclap.png"
        },


      {
            "name": "Improved Overpower",
            "description": "Increase the critical strike chance of your Overpower ability by %p%.",
            "values": {
                "%p": 25
            },
            "id": 6,
            "row": 2,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "inv_sword_05.png"
        },
      {
            "name": "Anger Management",
            "description": "Generates %p rage per 3 seconds while in combat.",
            "values": {
                "%p": 1
            },
            "id": 7,
            "row": 2,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "spell_holy_blessingofstamina.png"
        },
      {
            "name": "Deep Wounds",
            "description": "Your critical strikes cause the opponent to bleed, dealing %p% of your melee weapon's average damage over 12 seconds.",
            "values": {
                "%p": 20
            },
            "id": 8,
            "row": 2,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "ability_backstab.webp"
        },


      {
            "name": "Two-Handed Weapon Specialization",
            "description": "Increases the damage you deal with two-handed melee weapons by %p%.",
            "values": {
                "%p": 1
            },
            "id": 9,
            "row": 3,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "inv_axe_09.webp"
        },
      {
            "name": "Impale",
            "description": "Increases the critical strike damage bonus of your abilities in Battle, Defensive and Berserker stance by %p%.",
            "values": {
                "%p": 10
            },
            "id": 10,
            "row": 3,
            "col": 2,
            "max": 2,
            "current": 0,
            "image": "ability_searingarrow.png"
        },
      {
            "name": "Improved Slam",
            "description": "Decreases the casting time of your Slam ability by %p sec.",
            "values": {
                "%p": 0.5
            },
            "id": 11,
            "row": 3,
            "col": 3,
            "max": 2,
            "current": 0,
            "image": "ability_warrior_decisivestrike.webp"
        },


      {
            "name": "Poleaxe Specialization",
            "description": "Increases your chance to get a critical strike with Axes and Polearms by %p%.",
            "values": {
                "%p": 1
            },
            "id": 12,
            "row": 4,
            "col": 0,
            "max": 5,
            "current": 0,
            "image": "inv_axe_06.png"
        },
      {
            "name": "Sweeping Strikes",
            "description": "Your next %p melee attacks strike an additional nearby opponent.",
            "values": {
                "%p": 10
            },
            "id": 13,
            "row": 4,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "ability_rogue_slicedice.png",
            "type": "ability"
        },
      {
            "name": "Mace Specialization",
            "description": "Gives your melee attacks a chance to stun your target for 3 seconds and generate %p rage when using a mace.",
            "values": {
                "%p": 7
            },
            "id": 14,
            "row": 4,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "ability_warrior_decisivestrike.webp"
        },
      {
            "name": "Sword Specialization",
            "description": "Gives you a %p% chance to get an extra attack on the same target after hittin your target with your Sword.",
            "values": {
                "%p": 1
            },
            "id": 15,
            "row": 4,
            "col": 3,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Improved Intercept",
            "description": "Reduces the cooldown of your Intercept ability by %p sec.",
            "values": {
                "%p": 5
            },
            "id": 16,
            "row": 5,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "ability_warrior_victoryrush.webp"
        },
      {
            "name": "Improved Hamstring",
            "description": "Gives your Hamstring ability a %p% chance to immobilize the target for 5 seconds.",
            "values": {
                "%p": 2
            },
            "id": 17,
            "row": 5,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "ability_shockwave.webp"
        },
      {
            "name": "Improved Disiplines",
            "description": "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by %p min and increases their duration by %s sec.",
            "values": {
                "%p": 4,
                "%s": 2
            },
            "id": 18,
            "row": 5,
            "col": 3,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_improveddisciplines.webp"
        },


      {
            "name": "Blood Frenzy",
            "description": "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by %p%.",
            "values": {
                "%p": 2
            },
            "id": 19,
            "row": 6,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "ability_warrior_bloodfrenzy.webp"
        },
      {
            "name": "Mortal Strike",
            "description": "A viscious strike that deals weapon damage plus %p and wounds the target, reducing the effectiveness of any healing by 50% for 10 seconds.",
            "values": {
                "%p": 88
            },
            "id": 20,
            "row": 6,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "ability_warrior_savageblow.png",
            "type": "ability"
        },
      {
            "name": "Second Wind",
            "description": "Whenever you are struck by a Stun or Immobilize effect you will generate %r rage and %p% of your total health over 10 seconds.",
            "values": {
                "%p": 5,
                "%r": 10
            },
            "id": 21,
            "row": 6,
            "col": 2,
            "max": 2,
            "current": 0,
            "image": "ability_hunter_harass.png"
        },


      {
            "name": "Endless Rage",
            "description": "You generate %p% more rage from damage dealt.",
            "values": {
                "%p": 8
            },
            "id": 22,
            "row": 7,
            "col": 1,
            "max": 3,
            "current": 0,
            "image": "ability_warrior_endlessrage.png"
        },
      {
            "name": "Empowered Rend",
            "description": "The damage dealt by Rend is %p seconds faster.",
            "values": {
                "%p": 0.5
            },
            "id": 23,
            "row": 7,
            "col": 2,
            "max": 2,
            "current": 0,
            "image": "ability_gouge.png"
        },


      {
            "name": "Bladestorm",
            "description": "Instantly Whirlwind up to 4 nearby targets and for thr next 6 seconds you will perform a whirlwind attack every 1 sec. <br> While under the effects of Bladestorm, you can move but cannot perform any other abilities but you do not feel pity or remorse or fear, you cannot be stopped unless killed, and your movement speed cannot be reduced below 60%.",
            "values": {},
            "id": 24,
            "row": 8,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "ability_warrior_bladestorm.png",
            "type": "ability"
        },
    ]
  },
  "fury": {
    "image": "background-warrior-fury.png",
    "total": 0,
    "max": 60,
    "talents": [
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 0,
            "row": 0,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 1,
            "row": 0,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 2,
            "row": 1,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 3,
            "row": 1,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 4,
            "row": 2,
            "col": 0,
            "max": 3,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 5,
            "row": 2,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 6,
            "row": 2,
            "col": 2,
            "max": 3,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 7,
            "row": 2,
            "col": 3,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 8,
            "row": 3,
            "col": 1,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 9,
            "row": 3,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 10,
            "row": 4,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 11,
            "row": 4,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 12,
            "row": 4,
            "col": 3,
            "max": 2,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 13,
            "row": 5,
            "col": 0,
            "max": 2,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 14,
            "row": 5,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 15,
            "row": 6,
            "col": 0,
            "max": 3,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 16,
            "row": 6,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "inv_sword_27.png"
        },
      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 17,
            "row": 6,
            "col": 2,
            "max": 2,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 18,
            "row": 7,
            "col": 2,
            "max": 5,
            "current": 0,
            "image": "inv_sword_27.png"
        },


      {
            "name": "Divine Strength",
            "description": "Increases your total Strength by %p%.",
            "values": {
                "%p": 2
            },
            "id": 19,
            "row": 8,
            "col": 1,
            "max": 1,
            "current": 0,
            "image": "inv_sword_27.png"
        },
    ]
  },
  "protection": {
    "image": "background-warrior-protection.png",
    "total": 0,
    "max": 60,
    "talents": [
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 0,
        "row": 0,
        "col": 0,
        "max": 2,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 1,
        "row": 0,
        "col": 1,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 2,
        "row": 0,
        "col": 2,
        "max": 5,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 3,
        "row": 1,
        "col": 1,
        "max": 5,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 4,
        "row": 1,
        "col": 2,
        "max": 5,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 5,
        "row": 2,
        "col": 0,
        "max": 1,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 6,
        "row": 2,
        "col": 1,
        "max": 1,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 7,
        "row": 2,
        "col": 2,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 8,
        "row": 2,
        "col": 3,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 9,
        "row": 3,
        "col": 0,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 10,
        "row": 3,
        "col": 1,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 11,
        "row": 3,
        "col": 2,
        "max": 2,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 12,
        "row": 4,
        "col": 0,
        "max": 2,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 13,
        "row": 4,
        "col": 1,
        "max": 1,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 14,
        "row": 4,
        "col": 2,
        "max": 2,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 15,
        "row": 5,
        "col": 0,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 16,
        "row": 5,
        "col": 2,
        "max": 5,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 17,
        "row": 6,
        "col": 0,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 18,
        "row": 6,
        "col": 1,
        "max": 1,
        "current": 0,
        "image": "inv_sword_27.png"
      },
      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 19,
        "row": 6,
        "col": 2,
        "max": 3,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 20,
        "row": 7,
        "col": 1,
        "max": 5,
        "current": 0,
        "image": "inv_sword_27.png"
      },


      {
        "name": "Divine Strength",
        "description": "Increases your total Strength by %p%.",
        "values": {
            "%p": 2
        },
        "id": 21,
        "row": 8,
        "col": 1,
        "max": 1,
        "current": 0,
        "image": "inv_sword_27.png"
      },
    ]
  },
};
